export const AGREGAR_USUARIO_DISPONIBLE = "AGREGAR_USUARIO_DISPONIBLE";
export const BORRAR_USUARIO_DISPONIBLE = "BORRAR_USUARIO_DISPONIBLE";
export const AGREGAR_USUARIO_ORIGINAL = "AGREGAR_USUARIO_ORIGINAL";
export const AGREGAR_TERCERO_DISPONIBLE = "AGREGAR_TERCERO_DISPONIBLE";
export const OBTENER_INFORMACION_ADICIONAL_NUEVA_RADICACION =
  "OBTENER_INFORMACION_ADICIONAL_NUEVA_RADICACION";
export const INFO_ADICION_FORM_STEP1 = "INFO_ADICION_FORM_STEP1";
export const ARRAY_USERS_INFO_ADICIONAL_FORM_STEP1 =
  "ARRAY_USERS_INFO_ADICIONAL_FORM_STEP1";
export const OBTENER_DATA_PLANTILLA = "OBTENER_DATA_PLANTILLA";
export const OBTENER_METADATOS_PLANTILLA = "OBTENER_METADATOS_PLANTILLA";
export const OBTENER_INFO_PLANTILLA = "OBTENER_INFO_PLANTILLA";
export const OBTENER_METADATOS_ERROR = "OBTENER_METADATOS_ERROR";
export const RESET_FORM_STEP_1 = "RESET_FORM_STEP_1";
export const OBTENER_PLANTILLA_BY_TYPE_DOCUMENTARY =
  "OBTENER_PLANTILLA_BY_TYPE_DOCUMENTARY";
export const OBTENER_METADATOS_PLANTILLA_BY_TYPE_DOCUMENTARY =
  "OBTENER_METADATOS_PLANTILLA_BY_TYPE_DOCUMENTARY";
export const OBTENER_METADATOS_ERROR_BY_TYPE_DOCUMENTARY =
  "OBTENER_METADATOS_ERROR_BY_TYPE_DOCUMENTARY";
