export const AGREGAR_USUARIO_DISPONIBLE = "AGREGAR_USUARIO_DISPONIBLE";
export const BORRAR_USUARIO_DISPONIBLE = "BORRAR_USUARIO_DISPONIBLE";
export const AGREGAR_USUARIO_ORIGINAL = "AGREGAR_USUARIO_ORIGINAL";
export const AGREGAR_TERCERO_DISPONIBLE = "AGREGAR_TERCERO_DISPONIBLE";
export const OBTENER_INFORMACION_ADICIONAL_NUEVA_RADICACION =
  "OBTENER_INFORMACION_ADICIONAL_NUEVA_RADICACION";
export const INFO_ADICION_FORM_STEP1 = "INFO_ADICION_FORM_STEP1";
export const ARRAY_USERS_INFO_ADICIONAL_FORM_STEP1 =
  "ARRAY_USERS_INFO_ADICIONAL_FORM_STEP1";
<<<<<<< HEAD
export const OBTENER_DATA_PLANTILLA = "OBTENER_DATA_PLANTILLA";
export const OBTENER_METADATOS_PLANTILLA = "OBTENER_METADATOS_PLANTILLA";
export const OBTENER_INFO_PLANTILLA = "OBTENER_INFO_PLANTILLA";
export const OBTENER_METADATOS_ERROR = "OBTENER_METADATOS_ERROR";
=======

/* Types de Sticker */
export const OBTENER_DATOS_STICKER = "OBTENER_DATOS_STCKER";
export const OBTENER_DATOS_STICKER_EXITO = "OBTENER_DATOS_STICKER_EXITO";
export const OBTENER_DATOS_STICKER_ERROR = "OBTENER_DATOS_STICKER_ERROR";
/* Fin */
>>>>>>> 961982cf82f1951add0c6f95a359bac039042ae2
