export const AGREGAR_USUARIO_DISPONIBLE = "AGREGAR_USUARIO_DISPONIBLE";
export const BORRAR_USUARIO_DISPONIBLE = "BORRAR_USUARIO_DISPONIBLE";
export const AGREGAR_USUARIO_ORIGINAL = "AGREGAR_USUARIO_ORIGINAL";
export const AGREGAR_TERCERO_DISPONIBLE = "AGREGAR_TERCERO_DISPONIBLE";
export const OBTENER_INFORMACION_ADICIONAL_NUEVA_RADICACION =
  "OBTENER_INFORMACION_ADICIONAL_NUEVA_RADICACION";
export const INFO_ADICION_FORM_STEP1 = "INFO_ADICION_FORM_STEP1";
export const ARRAY_USERS_INFO_ADICIONAL_FORM_STEP1 =
  "ARRAY_USERS_INFO_ADICIONAL_FORM_STEP1";

export const OBTENER_DATA_PLANTILLA = "OBTENER_DATA_PLANTILLA";
export const OBTENER_METADATOS_PLANTILLA = "OBTENER_METADATOS_PLANTILLA";
export const OBTENER_INFO_PLANTILLA = "OBTENER_INFO_PLANTILLA";
export const OBTENER_METADATOS_ERROR = "OBTENER_METADATOS_ERROR";

export const OBTENER_DATOS_STICKER = "OBTENER_DATOS_STICKER";
export const OBTENER_DATOS_STICKER_EXITO = "OBTENER_DATOS_STICKER_EXITO";
export const OBTENER_DATOS_STICKER_ERROR = "OBTENER_DATOS_STICKER_ERROR";

export const OBTENER_STICKER = "OBTENER_STICKER";
export const OBTENER_STICKER_EXITO = "OBTENER_STICKER_EXITO";
export const OBTENER_STICKER_ERROR = "OBTENER_STICKER_ERROR";
export const RESET_FORM_STEP_1 = "RESET_FORM_STEP_1";
export const OBTENER_PLANTILLA_BY_TYPE_DOCUMENTARY =
  "OBTENER_PLANTILLA_BY_TYPE_DOCUMENTARY";
export const OBTENER_METADATOS_PLANTILLA_BY_TYPE_DOCUMENTARY =
  "OBTENER_METADATOS_PLANTILLA_BY_TYPE_DOCUMENTARY";
export const OBTENER_METADATOS_ERROR_BY_TYPE_DOCUMENTARY =
  "OBTENER_METADATOS_ERROR_BY_TYPE_DOCUMENTARY";
export const DATA_DETAILS_STICKER = "DATA_DETAILS_STICKER";
export const DATA_TITLE_STICKER = "DATA_TITLE_STICKER";
export const OBTENER_ID_RADICACION = "OBTENER_ID_RADICACION";

export const OBTENER_DATA_USER = "OBTENER_DATA_USER";
export const OBTENER_DATA_USER_EXITO = "OBTENER_DATA_USER_EXITO";
export const OBTENER_DATA_USER_ERROR = "OBTENER_DATA_USER_ERROR";
export const OBTENER_IMG_USER = "OBTENER_IMG_USER";
export const OBTENER_IMG_USER_EXITO = "OBTENER_IMG_USER_EXITO";
export const CAMBIAR_PASSWORD_USER = "CAMBIAR_PASSWORD_USER";
export const CAMBIAR_PASSWORD_USER_EXITO = "CAMBIAR_PASSWORD_USER_EXITO";
export const CAMBIAR_PASSWORD_USER_ERROR = "CAMBIAR_PASSWORD_USER_ERROR";

export const OBTENER_DATA_VISUALIZAR_RADICACION =
  "OBTENER_DATA_VISUALIZAR_RADICACION";

export const DATA_ALL_CORRESPONDENCE = "DATA_ALL_CORRESPONDENCE";
export const DATA_ALL_CORRESPONDENCE_PENDING =
  "DATA_ALL_CORRESPONDENCE_PENDING";

export const OBTENER_DATA_EXTERNA_CORRESPONDENCE =
  "OBTENER_DATA_EXTERNAL_CORRESPONDENCE";
export const OBTENER_DATA_EXTERNA_CORRESPONDENCE_EXITO =
  "OBTENER_DATA_EXTERNAL_CORRESPONDENCE_EXITO";
export const OBTENER_DATA_EXTERNA_CORRESPONDENCE_ERROR =
  "OBTENER_DATA_EXTERNAL_CORRESPONDENCE_ERROR";

export const OBTENER_DATA_EXTERNA_CORRESPONDENCE_PENDING =
  "OBTENER_DATA_EXTERNAL_CORRESPONDENCE_PENDING";
export const OBTENER_DATA_EXTERNA_CORRESPONDENCE_PENDING_EXITO =
  "OBTENER_DATA_EXTENA_CORRESPONDENCE_PENDING_EXITO";
export const OBTENER_DATA_EXTERNA_CORRESPONDENCE_PENDING_ERROR =
  "OBTENER_DATA_EXTERNA_CORRESPONDENCE_PENDING_ERROR";

export const VIEW_STEP_1 = "VIEW_STEP_1";
export const VIEW_STEP_2 = "VIEW_STEP_2";
export const VIEW_STEP_3 = "VIEW_STEP_3";
export const VIEW_STEP_4 = "VIEW_STEP_4";
